### ISSUE TITLE
Objective "Craft Camoes Bifana" should be of type FetchKeep

### ISSUE THREAD

**Issue by ar7max** [War3zuk/War3zuk-Alpha-20-Stable-AIO-2022#5]
Current config: `<objective type="Craft" id="Camoes Bifana" value="5" phase="2"/>` which works like "craft 5 Camoes Bifana in a row". My guess is that it should be of type "FetchKeep" since we can't acquire that item with looting.

**Comment by War3zuk** [comment]
Ill check thanks.. that code can cause issues when flipped which is prob why its that way

**Comment by ar7max** [comment]
ok, did some research, only 1 objective from Darkness Falls is of type craft and count > 1, all others (even vanilla one's) are count=1. Explains all, and I cant see any sane way of migrating from Craft to FetchKeep without restructuring whole quests tree. Sry for trouble you.

**Comment by War3zuk** [comment]
No worries thats why its set that way
